### ISSUE TITLE
Gradle can not complete build

### ISSUE THREAD

**Issue by ionutandone** [ranaparamveer/android-sqlite-asset-helper#1]
Whenever I try to build the project, I get the following error:

Failed to resolve: com.github.ranaparamveer:android-sqlite-asset-helper:v2.0.4

**Comment by ranaparamveer** [comment]
Please add :    **maven { url 'https://jitpack.io' }**  to project level gradle file under allprojects as:


```

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}
```
